name: Release SiroSDK

on:
  push:
    branches:
      - main
    paths:
      - "SiroSDK.podspec.json"
      - "ios/SiroSDK.xcframework"
  workflow_dispatch:

jobs:
  release:
    runs-on: macos-latest
    name: Push SiroSDK to cocoapods
    environment: production
    steps:
      - uses: actions/checkout@v4
      - name: Publish to SiroSDK to CocoaPods
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        run: |
          pod trunk push SiroSDK.podspec.json --verbose --allow-warnings --skip-import-validation --skip-tests
